### ISSUE TITLE
Add test results for Chrome

### ISSUE THREAD

**Issue by ZoeBijl** [MichielBijl/language-switch#1]
Maybe also with ChromeVox?

**Comment by garcialo** [comment]
Added test for ChromeVox, Chrome on Windows 10.
Close after adding one for Mac?

**Comment by ZoeBijl** [comment]
Yes. Will add OS X results today.

**Comment by ZoeBijl** [comment]
Fixed in: https://github.com/MichielBijl/language-switch/commit/c1a94acfe5ee142687fe7764d60a1fcf70cd4a32 and https://github.com/MichielBijl/language-switch/commit/d4badd1001bbae13bd4dcf29f39d33d2d857a0bb
